# Use this file to deploy the container for the tabletop combat helper API
# and the container for the Extensible Service Proxy (ESP) to
# Google Kubernetes Engine (GKE).

apiVersion: v1
kind: Service
metadata:
  name: esp-tabletop-combat-helper-api
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-tabletop-combat-helper-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-tabletop-combat-helper-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-tabletop-combat-helper-api
    spec:
      volumes:
      - name: service-account-creds
        secret:
          secretName: service-account-creds
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1.16.0
        args: [
          "--http2_port=9000",
          "--service=tch-api.endpoints.tabletop-combat-helper.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8000"
        ]
        ports:
          - containerPort: 9000
        volumeMounts:
        - name: service-account-creds
          mountPath: /etc/nginx/creds
          readOnly: true
      - name: tch-api
        image: gcr.io/tabletop-combat-helper/tch-api:1
        ports:
          - containerPort: 8000
